version: "3"
services:
  postgres-service:
    container_name: postgres-container
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres-network
 
  pgadmin:
    links:
    - postgres-service:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres-network
 
networks:
  postgres-network:
    driver: bridge